eps: 0.001
#eval_mode: False
eval_mode: True

# optimizer
lr: 0.0001
# train
data_dir: '/mnt/8T/home/estar/data/DanceTrack/trackers_gt'
diffnet: HMINet
interval: 5
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 800
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0,1,2,3]

# Testing
eval_at: 800
det_dir: "/mnt/8T/home/estar/data/DanceTrack/detections/val"
info_dir: '/mnt/8T/home/estar/data/DanceTrack/val'
reid_dir: "/home/estar/lwy/DiffMOT/cache/embeddings/"
save_dir: "/mnt/8T/home/estar/data/DanceTrack/results/val/yolox_m_lt_ddm_1000eps_deeper_800_1rev"
eval_expname: lt_ddm_1000_deeper
high_thres: 0.6
low_thres: 0.4
w_assoc_emb: 2.2
aw_param: 1.7
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: None
